"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import environ
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
# read_env 는 이미 설정된 환경변수를 덮어쓰지 않는다. 그래서 컨테이너에서는
# compose 의 env_file 이 이기고, .env 파일은 로컬 개발용 기본값으로만 남는다.
environ.Env.read_env(str(BASE_DIR / ".env"))

# 기본값을 두지 않는다. 시크릿이 없으면 뜨지 않고 바로 죽는 쪽이,
# 개발용 키로 운영이 돌아가는 것보다 낫다.
SECRET_KEY = env("DJANGO_SECRET_KEY")

# 기본 False. DEBUG 가 켜지면 아래 REST_FRAMEWORK 권한이 AllowAny 로 바뀌어
# API 전체가 무인증으로 열리므로, 실수로 켜지는 일이 없어야 한다.
DEBUG = env.bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "corsheaders",
    "users",
    "parking_management",
    'drf_spectacular',
    'drf_spectacular_sidecar',
    "core",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated" if not DEBUG else "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# 프론트는 nginx 가 /api 를 같은 출처로 프록시하므로 운영에서는 CORS 가 필요 없다.
# 개발에서 Vite 를 따로 띄울 때만 전체 허용으로 떨어진다.
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = env.list("DJANGO_CORS_ALLOWED_ORIGINS", default=[])

# DEBUG=False 에서 admin 로그인 같은 POST 가 통과하려면 출처를 scheme 까지 적어야 한다.
CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS", default=[])

# TLS 는 앞단 nginx 가 끊고 내부로는 평문으로 넘어온다. 이 설정이 없으면 Django 가
# 자신을 http 로 알아 리다이렉트가 http 로 나가고 CSRF 출처 검사가 어긋난다.
# nginx.conf 가 X-Forwarded-Proto 를 넣어 주는 것을 전제로 한다.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# https 로 전환한 뒤에 켠다. http 로 서비스하는 동안 켜면 쿠키가 전송되지 않아
# 로그인이 되지 않는다.
SESSION_COOKIE_SECURE = env.bool("DJANGO_SECURE_COOKIES", default=False)
CSRF_COOKIE_SECURE = env.bool("DJANGO_SECURE_COOKIES", default=False)

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,

    "AUTH_HEADER_TYPES": ("Bearer",),
}

ROOT_URLCONF = "core.urls"

SPECTACULAR_SETTINGS = {
    "TITLE": "Django JWT API",
    "DESCRIPTION": "Django REST Framework JWT Authentication API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# env(json)에서 ACTIVE_DB값을 찾음, 없으면 default 사용
ACTIVE_DB = env("ACTIVE_DB", default="dev")

DATABASES = {
    "prod": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("PROD_DB_NAME"),
        "USER": env("PROD_DB_USER"),
        "PASSWORD": env("PROD_DB_PASSWORD"),
        "HOST": env("PROD_DB_HOST"),
        "PORT": env("PROD_DB_PORT"),
    },
    "staging": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("STAGING_DB_NAME"),
        "USER": env("STAGING_DB_USER"),
        "PASSWORD": env("STAGING_DB_PASSWORD"),
        "HOST": env("STAGING_DB_HOST"),
        "PORT": env("STAGING_DB_PORT"),
    },
    "dev": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DEV_DB_NAME"),
        "USER": env("DEV_DB_USER"),
        "PASSWORD": env("DEV_DB_PASSWORD"),
        "HOST": env("DEV_DB_HOST"),
        "PORT": env("DEV_DB_PORT"),
    },
}
DATABASES["default"] = DATABASES[ACTIVE_DB]

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "ko-kr"
TIME_ZONE = "Asia/Seoul"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = []

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
