# Generated by Django 5.0.7 on 2026-07-01 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.CharField(db_comment='유저아이디', max_length=200, primary_key=True, serialize=False)),
                ('dong_ho_id', models.IntegerField(blank=True, db_comment='동호수ID', null=True)),
                ('user_name', models.CharField(blank=True, db_comment='유저명', max_length=100)),
                ('phone_number', models.CharField(blank=True, db_comment='연락처', max_length=30)),
                ('is_deleted', models.BooleanField(blank=True, db_comment='삭제여부')),
            ],
            options={
                'db_table': '"parking_lot"."user_profile"',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(db_comment='차량ID', primary_key=True, serialize=False)),
                ('parking_type', models.CharField(blank=True, db_comment='주차유형', max_length=100)),
                ('vehicle_type', models.CharField(blank=True, db_comment='차종', max_length=100)),
                ('model_name', models.CharField(blank=True, db_comment='모델명', max_length=100, null=True)),
                ('plate_number', models.CharField(blank=True, db_comment='차량번호', max_length=200, null=True)),
                ('color', models.CharField(blank=True, db_comment='색상', max_length=20, null=True)),
                ('tower_yn', models.BooleanField(blank=True, db_comment='타워가능여부')),
                ('attachment_file_id', models.IntegerField(blank=True, db_comment='첨부파일ID', null=True)),
                ('remarks', models.TextField(blank=True, db_comment='비고', null=True)),
                ('is_deleted', models.BooleanField(blank=True, db_comment='삭제여부')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', db_comment='유저아이디', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='parking_management.userprofile')),
            ],
            options={
                'db_table': '"parking_lot"."vehicles"',
            },
        ),
    ]
