# Generated by Django 5.0.7 on 2026-07-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0002_attachmentfile_unauthorizedparkingrecord_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitant',
            name='parking_end_time',
            field=models.DateTimeField(blank=True, db_comment='주차종료시각', null=True),
        ),
        migrations.AddField(
            model_name='visitant',
            name='parking_start_time',
            field=models.DateTimeField(blank=True, db_comment='주차시작시각', null=True),
        ),
    ]
