# Generated by Django 5.0.7 on 2026-07-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0003_visitant_parking_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dongho',
            name='exp_resi_end_date',
        ),
        migrations.RemoveField(
            model_name='dongho',
            name='exp_resi_start_date',
        ),
        migrations.RemoveField(
            model_name='dongho',
            name='temp_resi_end_date',
        ),
        migrations.RemoveField(
            model_name='dongho',
            name='temp_resi_start_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exp_resi_end_date',
            field=models.DateField(blank=True, db_comment='예상거주종료일', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exp_resi_start_date',
            field=models.DateField(blank=True, db_comment='예상거주시작일', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='residence_type',
            field=models.CharField(blank=True, db_comment='거주유형', max_length=50, null=True),
        ),
    ]
