# Generated by Django 5.0.7 on 2026-07-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_management", "0004_remove_dongho_exp_resi_end_date_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("plate_number",),
                name="uq_vehicles_plate_number",
            ),
        ),
    ]
