# Generated by Django 5.0.7 on 2026-07-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_management", "0005_vehicle_uq_vehicles_plate_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitant",
            name="valid_hours",
            field=models.IntegerField(blank=True, db_comment="가능시간", null=True),
        ),
    ]
