version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: parking_lot_backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "5174:8000"
    restart: always

  # redis:
  #   image: redis:7
  #   container_name: parking_lot_redis
  #   ports:
  #     - "6381:6379"
  #   restart: always