# Generated by Django 5.0.7 on 2026-07-01 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachmentFile",
            fields=[
                (
                    "attachment_file_id",
                    models.AutoField(
                        db_comment="첨부파일ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "attachment_table",
                    models.CharField(
                        blank=True, db_comment="첨부테이블", max_length=200
                    ),
                ),
                ("search_id", models.IntegerField(blank=True, db_comment="조회ID")),
                ("file_url", models.TextField(blank=True, db_comment="파일URL")),
                (
                    "file_name",
                    models.CharField(
                        blank=True, db_comment="원본파일명", max_length=200
                    ),
                ),
                ("file_size", models.IntegerField(blank=True, db_comment="파일크기")),
                (
                    "mime_type",
                    models.CharField(blank=True, db_comment="MIME종류", max_length=100),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, db_comment="정렬순서", null=True),
                ),
                (
                    "created_at",
                    models.DateField(blank=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(blank=True, db_comment="수정일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                ("is_deleted", models.BooleanField(blank=True, db_comment="삭제여부")),
            ],
            options={
                "db_table": '"parking_lot"."attachment_files"',
            },
        ),
        migrations.CreateModel(
            name="UnauthorizedParkingRecord",
            fields=[
                (
                    "vehicle_id",
                    models.AutoField(
                        db_comment="차량ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(blank=True, db_comment="차량번호", max_length=200),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, db_comment="연락처", max_length=30, null=True
                    ),
                ),
                (
                    "parking_start_time",
                    models.DateTimeField(blank=True, db_comment="주차시작시각"),
                ),
                (
                    "parking_end_time",
                    models.DateTimeField(
                        blank=True, db_comment="주차종료시각", null=True
                    ),
                ),
                (
                    "parking_location",
                    models.CharField(blank=True, db_comment="추자위치", max_length=100),
                ),
                (
                    "attachment_file_id",
                    models.IntegerField(blank=True, db_comment="첨부파일ID", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                ("is_deleted", models.BooleanField(blank=True, db_comment="삭제여부")),
            ],
            options={
                "db_table": '"parking_lot"."unauthorized_parking_records"',
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "comments_id",
                    models.AutoField(
                        db_comment="댓글ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "reply_count",
                    models.IntegerField(blank=True, db_comment="대댓글수", null=True),
                ),
                (
                    "depth",
                    models.IntegerField(blank=True, db_comment="수준", null=True),
                ),
                (
                    "content",
                    models.TextField(blank=True, db_comment="댓글내용", null=True),
                ),
                (
                    "like_count",
                    models.IntegerField(
                        blank=True, db_comment="댓글좋아요수", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateField(blank=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(blank=True, db_comment="수정일", null=True),
                ),
                (
                    "deleted_at",
                    models.DateField(blank=True, db_comment="삭제일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                ("is_deleted", models.BooleanField(blank=True, db_comment="삭제여부")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_id",
                        db_comment="부모ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="parking_management.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        db_comment="유저ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to="parking_management.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": '"parking_lot"."comments"',
            },
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "comments_like_id",
                    models.AutoField(
                        db_comment="댓글좋아요ID", primary_key=True, serialize=False
                    ),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                ("is_deleted", models.BooleanField(blank=True, db_comment="삭제여부")),
                (
                    "comment",
                    models.ForeignKey(
                        db_column="comments_id",
                        db_comment="댓글ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_likes",
                        to="parking_management.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        db_comment="유저ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comment_likes",
                        to="parking_management.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": '"parking_lot"."comments_like"',
            },
        ),
        migrations.CreateModel(
            name="DongHo",
            fields=[
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "dong_ho_id",
                    models.AutoField(
                        db_comment="동호수ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "dong_ho_name",
                    models.CharField(blank=True, db_comment="동호수명", max_length=100),
                ),
                (
                    "exp_resi_start_date",
                    models.DateField(
                        blank=True, db_comment="예상거주시작일", null=True
                    ),
                ),
                (
                    "exp_resi_end_date",
                    models.DateField(
                        blank=True, db_comment="예상거주종료일", null=True
                    ),
                ),
                (
                    "temp_resi_start_date",
                    models.DateField(
                        blank=True, db_comment="임시거주시작일", null=True
                    ),
                ),
                (
                    "temp_resi_end_date",
                    models.DateField(
                        blank=True, db_comment="임시거주종료일", null=True
                    ),
                ),
                (
                    "admin_check",
                    models.BooleanField(blank=True, db_comment="관리자확인", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        db_comment="유저아이디",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dong_hos",
                        to="parking_management.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": '"parking_lot"."dong_ho"',
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "posts_id",
                    models.AutoField(
                        db_comment="게시글ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "posts_type",
                    models.CharField(
                        blank=True, db_comment="게시판유형", max_length=20, null=True
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, db_comment="노출순서", null=True),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, db_comment="제목", max_length=200, null=True
                    ),
                ),
                ("content", models.TextField(blank=True, db_comment="본문", null=True)),
                (
                    "is_pinned",
                    models.BooleanField(blank=True, db_comment="상단고정여부"),
                ),
                (
                    "view_count",
                    models.IntegerField(blank=True, db_comment="조회수", null=True),
                ),
                (
                    "comment_count",
                    models.IntegerField(blank=True, db_comment="댓글수", null=True),
                ),
                (
                    "like_count",
                    models.IntegerField(blank=True, db_comment="좋아요수", null=True),
                ),
                (
                    "attachment_file_id",
                    models.IntegerField(blank=True, db_comment="첨부파일ID", null=True),
                ),
                (
                    "created_at",
                    models.DateField(blank=True, db_comment="생성일", null=True),
                ),
                (
                    "updated_at",
                    models.DateField(blank=True, db_comment="수정일", null=True),
                ),
                (
                    "deleted_at",
                    models.DateField(blank=True, db_comment="삭제일", null=True),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                ("is_deleted", models.BooleanField(blank=True, db_comment="삭제여부")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        db_comment="유저ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="parking_management.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": '"parking_lot"."posts"',
            },
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                blank=True,
                db_column="posts_id",
                db_comment="게시글ID",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to="parking_management.post",
            ),
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                (
                    "posts_like_id",
                    models.AutoField(
                        db_comment="게시글좋아요ID", primary_key=True, serialize=False
                    ),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                ("is_deleted", models.BooleanField(blank=True, db_comment="삭제여부")),
                (
                    "post",
                    models.ForeignKey(
                        db_column="posts_id",
                        db_comment="게시글ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_likes",
                        to="parking_management.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        db_comment="유저ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="post_likes",
                        to="parking_management.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": '"parking_lot"."posts_like"',
            },
        ),
        migrations.CreateModel(
            name="Visitant",
            fields=[
                (
                    "visitant_id",
                    models.AutoField(
                        db_comment="방문자ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "visitant_name",
                    models.CharField(
                        blank=True, db_comment="방문자이름", max_length=100, null=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, db_comment="연락처", max_length=30, null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True, db_comment="비고", null=True)),
                ("is_deleted", models.BooleanField(blank=True, db_comment="삭제여부")),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        db_comment="유저아이디",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitants",
                        to="parking_management.userprofile",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        db_column="vehicle_id",
                        db_comment="차량ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitants",
                        to="parking_management.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": '"parking_lot"."visitants"',
            },
        ),
        migrations.AddConstraint(
            model_name="commentlike",
            constraint=models.UniqueConstraint(
                fields=("comment", "user"), name="uq_comments_like_comment_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="postlike",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="uq_posts_like_post_user"
            ),
        ),
    ]
